name = "capsule"
license = "GPL-2.0"
licenselink = "https://github.com/sudorook/capsule/blob/master/LICENSE"
description = "A CSS-only theme for Hugo using Bulma and Font-Awesome"
homepage = "https://github.com/sudorook/capsule"
tags = ["hugo", "bulma", "css-only", "font-awesome"]
features = []
min_version = 0.18

[author]
  name = "sudorook"
  homepage = ""
